In [83]:
import openai
import pandas as pd
import pandasql as ps
import time

messages = []
    
openai.api_key = "<YOUR_OPEN_AI_API_KEY>"
df_input = pd.read_csv('example.csv')
#user_prompt = "write a sql query to get the the count of activities for each user and sort by descending count"
user_prompt = "write a sql query to get the users who have activity related to AWS along with activity"

In [94]:
def ask_chatgpt(df_input,user_prompt):
    ai_model = "gpt-3.5-turbo"
    #ai_model = "gpt-3.5-turbo-0301"
    #ai_model = "davinci"
    system_msg = "sql"
    messages.append({"role": "system", "content": system_msg})
    messages.append({"role": "user", "content": "Hello"})
    #response = openai.ChatCompletion.create(
    #model=ai_model,
    #messages=messages)
    #reply = response["choices"][0]["message"]["content"]
    #messages.append({"role": "assistant", "content": "Hello! How can I assist you today?"})
    print("Step1 Completed")
    #time.sleep(2)
    
    df_query = df_input
    table_string = "i have a table with " + str(len(df_query.columns)) + " columns. Columns names are "
    for col in df_query.columns:
        table_string = table_string + col + ", "
    #print(table_string)
    #time.sleep(2)
    
    messages.append({"role": "user", "content": table_string})
    #response = openai.ChatCompletion.create(
    #model=ai_model,
    #messages=messages)
    #reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": "Okay, what would you like to do with this table? Does it need to be modified, queried, or something else?"})
    print("Step2 Completed")
    time.sleep(2)
    
    messages.append({"role": "user", "content": user_prompt})
    response = openai.ChatCompletion.create(
    model=ai_model,
    messages=messages)
    reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": reply})
    print("Step3 Completed")
    time.sleep(2)
    print(reply)
    sql_str = ""
    if reply.find('SELECT') > 0:
        sql_str = reply[reply.find('SELECT'):reply.find('Replace')-6]
        sql_str = sql_str.replace('\n',' ')
        sql_str = sql_str.replace(sql_str.split(" ")[sql_str.split(" ").index('FROM')+1],'df_query')
        print(sql_str)
    
    return ps.sqldf(sql_str)

In [95]:
start = time.time()
result = ask_chatgpt(df_input,user_prompt)
result
end = time.time()
print(end - start)

Step1 Completed
Step2 Completed
Step3 Completed
Sure, here is a possible SQL query to achieve this:

```
SELECT User, Activity
FROM your_table_name
WHERE Activity LIKE '%AWS%'
```

Replace "your_table_name" with the actual name of your table. This query will retrieve all the users and their associated activities which contains the word "AWS" in the Activity field.

Using the `LIKE` operator with `%` symbol allows us to match any activity string having the substring "AWS" in it.
SELECT User, Activity FROM df_query WHERE Activity LIKE '%AWS%'
30.773574352264404

In [96]:
result

,User,Activity
0,vijeth.kumar@derisk360.com,AWS
1,shweta.sachdev@derisk360.com,AWS Solution Architect Certification
2,sagarvijay.thosar@derisk360.com,Take a professional training course on infra m...
3,sanif.mujawar@derisk360.com,AWS Cloud Practitioner Certification
4,chitransh.srivastava@derisk360.com,AWS CCP
5,chitransh.srivastava@derisk360.com,AWS Associate Solution Architect
6,priyadharshini@derisk360.com,AWS Solutions Architect
7,gagan.kumar@derisk360.com,AWS Sysops
8,balaji.ramanujam@derisk360.com,AWS Data specialiy
9,mala.d@derisk360.com,Planning to complete Derisk 360 Lab activities...
10,prawin.veeramani@derisk360.com,AWS Data Analytics Specialisation
11,sripriya.sethuraman@derisk360.com,AWS

In [ ]:
def ask_chatgpt(df_input,user_prompt):
    ai_model = "gpt-3.5-turbo"
    #ai_model = "gpt-3.5-turbo-0301"
    #ai_model = "davinci"
    system_msg = "sql"
    messages.append({"role": "system", "content": system_msg})
    messages.append({"role": "user", "content": "Hello"})
    response = openai.ChatCompletion.create(
    model=ai_model,
    messages=messages)
    reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": reply})
    print("Step1 Completed")
    time.sleep(2)
    
    df_query = df_input
    table_string = "i have a table with " + str(len(df_query.columns)) + " columns. Columns names are "
    for col in df_query.columns:
        table_string = table_string + col + ", "
    #print(table_string)
    time.sleep(2)
    
    messages.append({"role": "user", "content": table_string})
    response = openai.ChatCompletion.create(
    model=ai_model,
    messages=messages)
    reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": reply})
    print("Step2 Completed")
    time.sleep(2)
    
    messages.append({"role": "user", "content": user_prompt})
    response = openai.ChatCompletion.create(
    model=ai_model,
    messages=messages)
    reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": reply})
    print("Step3 Completed")
    time.sleep(2)
    
    if reply.find('SELECT') > 0 and reply.find(';') > 0:
        sql_str = reply[reply.find('SELECT'):reply.find(';')]
        sql_str = sql_str.replace('\n',' ')
        sql_str = sql_str.replace(sql_str.split(" ")[sql_str.split(" ").index('FROM')+1],'df_query')
        print(sql_str)
    
    return ps.sqldf(sql_str)

In [89]:
x = "```
SELECT User, Activity
FROM your_table_name
WHERE Activity LIKE '%AWS%'
```"

SyntaxError: EOL while scanning string literal (2682183969.py, line 1)